version: "3"
services:
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile_${ENV}
    ports:
      - 3000:3000
    depends_on:
      - backend
    tty: true
    volumes:
      - ./front:/usr/src/app
    working_dir: "/usr/src/app"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile_${ENV}
    ports:
      - 3001:3001
    depends_on:
      - db
    tty: true
    volumes:
      - ./backend:/go/src/api
    working_dir: "/go/src/api"
    environment:
      DB_HOST: dockerMySQL
      DB_PORT: 3306
      DB_NAME: mydb
      DB_ROOTPASS: password
      DB_USERNAME: test
      DB_USERPASS: password
    # networks:
    #   - test-network
    # restart: always

  db:
    image: mysql
    container_name: dockerMySQL
    command: >
      mysqld
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/my.conf:/etc/mysql/my.conf"
    # networks:
    #   - test-network
    # restart: always
