version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.0.0
  aws-ecs: circleci/aws-ecs@1.1.0

jobs:
  test:
    machine: true

    steps:
      - checkout
      # - run:
      #     name: create docker network
      #     command: docker network create test-network
      # - run:
      #     name: コンテナ起動
      #     command: docker-compose up -d
      # - run:
      #     name: 静的デバッグ
      #     command: make lint
      # - run:
      #     name: テスト
      #     command: make test

workflows:
  version: 2
  workflow:
    jobs:
      - test
      # dockerイメージのビルド & ECRへプッシュ
      - aws-ecr/build-and-push-image:
          # テストをパスしたら実行
          requires:
            - test
          filters:
            branches:
              only: master
          region: AWS_DEFAULT_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: ${FRONT_REPO}
          tag: "${CIRCLE_SHA1}"
          dockerfile: ./front/Dockerfile
      # - aws-ecr/build-and-push-image:
      #     # テストをパスしたら実行
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: master
      #     region: AWS_DEFAULT_REGION
      #     account-url: AWS_ECR_ACCOUNT_URL
      #     repo: ${BACKEND_REPO}
      #     tag: "${CIRCLE_SHA1}"
      #     dockerfile: ./backend/Dockerfile
      - aws-ecs/deploy-service-update:
          # イメージのビルド & プッシュが成功したら実行
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: master
          aws-region: ${AWS_REGION}
          family: ${ECS_SERVICE}
          cluster-name: "${ECS_CLUSTER}"
          container-image-name-updates: "container=${ECS_SERVICE},image-and-tag=${AWS_ECR_ACCOUNT_URL}/${FRONT_REPO}:${CIRCLE_SHA1}"
