version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.2.1

jobs:
  test:
    machine: true

    steps:
      - checkout
      - run:
          name: create docker network
          command: docker network create test-network
      - run:
          name: コンテナ起動
          command: docker-compose up -d
      - run:
          name: jestインストール
          command: docker-compose exec front yarn add jest@26.0.1
      - run:
          name: フロントLint
          command: make front-lint
      - run:
          name: フロントエンドテスト
          command: make front-test
      - run:
          name: マイグレーション
          command: make backend-migrate
      - run:
          name: staticcheckインストール
          command: docker-compose exec backend go get honnef.co/go/tools/cmd/staticcheck@latest
      - run:
          name: バックエンドLint
          command: make backend-lint
      - run:
          name: バックエンドテスト
          command: make backend-test

workflows:
  version: 2
  front:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          requires:
            - test
          filters:
            branches:
              only: master
          region: AWS_DEFAULT_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: ${FRONT_REPO}
          tag: "latest"
          dockerfile: ./front/Dockerfile_prd
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: master
          family: "${FRONT_ECS_SERVICE}"
          cluster-name: "${FRONT_ECS_CLUSTER}"
          service-name: "${FRONT_ECS_SERVICE}"
          container-image-name-updates: "container=${FRONT_CONTAINER_NAME},tag=latest"
  backend:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          requires:
            - test
          filters:
            branches:
              only: master
          region: AWS_DEFAULT_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: ${BACKEND_REPO}
          tag: "latest"
          dockerfile: ./backend/Dockerfile_prd
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: master
          family: "${BACKEND_ECS_SERVICE}"
          cluster-name: "${BACKEND_ECS_CLUSTER}"
          service-name: "${BACKEND_ECS_SERVICE}"
          container-image-name-updates: "container=${BACKEND_ECS_CLUSTER},tag=latest"
