version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout

      - restore_cache:
          key: mod-{{ checksum "go.sum" }}

      - run: go get
      - run: go test -v ./...
      - run: go build -o main main.go

      - store_artifacts:
          path: main
          destination: main

      - save_cache:
          key: mod-{{ checksum "go.sum" }}
          paths:
            - $GOPATH/pkg/mod

  build_image:
    docker:
      - image: docker:18.09.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: install aws cli
        command: |
          apk add --no-cache --update py-pip
          pip install awscli
        - run:
          name: login ecr
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
        - run:
          name: build image
          command: |
          docker build -t ${ECR_DOMAIN}:$CIRCLE_SHA1 -t ${ECR_DOMAIN}:latest .
        - run:
          name: Push docker image
          command: |
            docker push ${ECR_DOMAIN}:$CIRCLE_SHA1 docker push ${ECR_DOMAIN}:latest
workflows:
  version: 2
  test:
    jobs:
      - build
      - build_image:
          requires:
            - build
          filters:
            branches:
              only: master
